### ISSUE TITLE
Using Ireport Table

### ISSUE THREAD

**Issue by thiagocifani** [rodrigomanhaes/rasper_client#5]
any possibility to use this gem with a jrxml table example?

**Comment by rodrigomanhaes** [comment]
When using tables, you should upload the table jrxml files and give the same name to both table jrxml file and report.

E.g., I have a report called "extrato" having

```xml
<subreport>
	<reportElement uuid="37db673e-8036-4c0d-b78c-5d07ae901cba" x="0" y="37" width="555" height="10"/>
	<dataSourceExpression><![CDATA[((net.sf.jasperreports.engine.data.JRXmlDataSource)$P{REPORT_DATA_SOURCE}).subDataSource("//formacoes/formaco")]]></dataSourceExpression>
	<subreportExpression><![CDATA["extratoformacoes.jasper"]]></subreportExpression>
</subreport>
```

and a `extratoformacoes.jrxml` file that should be uploaded by passing `{ name: "extratoformacoes", content: '...' }` to `RasperClient::Client#add`.

The XPath expression should match the structure you provide to `RasperClient::Client#generate`. If you have a non-english model, pay special attention to inflections, since rasper server uses Rails' defaults. In this example, the singularization of a word like "formacoes" will be "formaco".

Sorry for the long delay.

**Comment by rodrigomanhaes** [comment]
@thiagocifani Since this doesn't seem to be an issue with rasper_client, I'm closing it, ok?
